### ISSUE TITLE
Contact : send a message

### ISSUE THREAD

**Issue by arpita-addweb** [narendra-addweb/SwitchedOn#33]
Is the any mail is sending to admin from the functionality when the user tries to send any message for the inquiry

**Comment by narendra-addweb** [comment]
Currently we set mail send functionality as per below:
Email setup on demo server

For newsletter and contact page: johnnyharpertesting1@gmail.com

*_NOTE: *_ Contact page email functionality will send mail to site only where as newsletter subscription mail will send user email as well site both.

**Comment by arpita-addweb** [comment]
Closing the issue as per developer comment
