### ISSUE TITLE
Beliefs : Client Changes 

### ISSUE THREAD

**Issue by arpita-addweb** [narendra-addweb/SwitchedOn#52]
The Client New Changes mentioned below for Beliefs page   : 
For My Clients, I Believe In 
- The most magnificent version of you
- Your power to create your own reality
- Your ability to take care of yourself
- Your right to ask for what you want
- Your longing to act from the heart

For My Clients, I Believe In should be changed to  "For you, I believe in".

**Comment by narendra-addweb** [comment]
Made changes as per client comment: 
"Replace that text (into beliefs page) in "MY CLIENT, I BELIEVE IN" section please. "
