### ISSUE TITLE
About me : Timeline 

### ISSUE THREAD

**Issue by arpita-addweb** [narendra-addweb/SwitchedOn#57]
1.I noticed on the About Me page that there are quotation marks around the last paragraph of narratvie   (that begins with: Today, I live in and love London). Can those be taken out, please?
2. In terms of which dates to highlight on the timeline, I would go for 2011 and 2015. Unless it needs to be more balanced visually, in which case I’d go for 2004 and 2015.

**Comment by narendra-addweb** [comment]
Regarding point 2:
"In terms of which dates to highlight on the timeline, I would go for 2011 and 2015. Unless it needs to be more balanced visually, in which case I’d go for 2004 and 2015."

> > Make changes as per client recent comment: "Start with 1995 and making 2004 and 2015 big."

**Comment by arpita-addweb** [comment]
As per dev comment verified the update reported
