### ISSUE TITLE
About Me : Timeline

### ISSUE THREAD

**Issue by arpita-addweb** [narendra-addweb/SwitchedOn#58]
1. **1979 - 2000 *_should be replaced with ... *_2000**
2. **2000** : grow up in Belgium, South Africa and France should be replaced  with Grew up in Belgium, South Africa and France (like I was going to tell you how old I am!).
3. **1979** : Don't make her birthday standout .
4. Make **2001 **stand out instead.
   5.**2001*\* : Got my LL.M. from Cambridge University and moved to London - a dream comes true.
5. Make the lines of the Timeline  a bitter finer so they look like Timeline rather than ruler .
   7.**2004** : Decided that being a barrister wasn’t for me (barrister’s wig on curly hair: not a good look).       First time I considered changing careers.
   8.*\* 2006*\* : Fell into first corporate job. Thought I had finally figured it out.
   9: Need a more dynamic font as provided in the psd .
6. **2006** Fell into first corporate job. Thought I had finally figured it out.
7. **2011** Was miserable in my corporate job and desperate to get out. Met my mentor.
   12.*\* 2012 **Quit corporate job with no clue as to what I was going to do next. Went solo traveling across 3 continents.
8. **2013** Started a new corporate job as a result of meeting people on my travels.
9. **2014** Quit corporate job. Again.
10. **2015** Trained as a coach and set up my coaching practice.
11.  **2016** Enjoying the ride!.
12. Highlight the year on Timeline : **2011, 2015.**

**Comment by narendra-addweb** [comment]
Make changes as per client recent comment:
1. Change timeline data
   2000 Grew up in Belgium, South Africa and France (like I was going to tell you how old I am!)
   2001 Got my LL.M. from Cambridge University and moved to London - a dream comes true.
   2004 Decided that being a barrister wasn’t for me (barrister’s wig on curly hair: not a good look). First time I considered changing careers
   2006 Fell into first corporate job. Thought I had finally figured it out.
   2011 Was miserable in my corporate job and desperate to get out. Met my mentor.
   2012 Quit corporate job with no clue as to what I was going to do next. Went solo travelling across 3 continents.
   2013 Started a new corporate job as a result of meeting people on my travels.
   2014 Quit corporate job. Again.
   2015 Trained as a coach and set up my coaching practice.
   2016 Enjoying the ride!
2. Start with 1995 and making 2004 and 2015 big.
