### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by arpita-addweb** [narendra-addweb/SwitchedOn#66]
Responsive iPad(Landscape & Portrait)  Browser : Safari 
1. The banner content is colliding with the birds .

Responsive iPad & iPhone (Portrait)  Browser : Safari 
2. Get in Touch : The font colour of the Phone number is not as per the website .
3. Get In Touch : The Email should align with the Email icon .
4.Get in Touch form 4 th option "What are you getting in Touch about ?" field looks distorted .

**Comment by vivek-addweb** [comment]
For 1) we need to change parallax js. not working on i-phone device
points 2,3,4 are completed

**Comment by vivek-addweb** [comment]
We have used parallax js of purchased theme. Need not to change it.

**Comment by arpita-addweb** [comment]
As discussed with the team closing the issue
